package org.dubbo.spring.boot.tigerz.aus.entity;

import java.util.ArrayList;
import java.util.Map;

import org.elasticsearch.search.SearchHit;
import org.elasticsearch.search.SearchHits;

/**
 * This code is generated by Machine
 * @author wangjignci@126.com
 *
 */
public class School
{
    /********** attribute ***********/
    private java.lang.String _id;
     
    private java.lang.Integer schoolId;
     
    private java.lang.String schoolName;
     
    private java.lang.String email;
     
    private java.lang.String website;
     
    private java.lang.String sector;
     
    private java.lang.String gender;
     
    private java.lang.String type;
     
    private java.util.ArrayList basePoint;
     
    private java.lang.String address;
     
    private java.lang.String suburb;
     
    private java.lang.String streetName;
     
    private java.lang.String state;
     
    private java.lang.String postcode;
     
    private java.util.ArrayList polygon;
     
    private java.lang.Double eastBound;
     
    private java.lang.Double westBound;
     
    private java.lang.Double northBound;
     
    private java.lang.Double southBound;
     
    private java.lang.String linkUrl;
     
    private java.lang.String level;
     
    private java.lang.String year;
    
    private Integer rank;
     
    /********** constructors ***********/
    public School() {
     
    }
 
    public School(java.lang.String _id, java.lang.Integer schoolId, java.lang.String schoolName, java.lang.String email, java.lang.String website, java.lang.String sector, java.lang.String gender, java.lang.String type, java.util.ArrayList basePoint, java.lang.String address, java.lang.String suburb, java.lang.String streetName, java.lang.String state, java.lang.String postcode, java.util.ArrayList polygon, java.lang.Double eastBound, java.lang.Double westBound, java.lang.Double northBound, java.lang.Double southBound, java.lang.String linkUrl, java.lang.String level, java.lang.String year) {
        this._id = _id;
        this.schoolId = schoolId;
        this.schoolName = schoolName;
        this.email = email;
        this.website = website;
        this.sector = sector;
        this.gender = gender;
        this.type = type;
        this.basePoint = basePoint;
        this.address = address;
        this.suburb = suburb;
        this.streetName = streetName;
        this.state = state;
        this.postcode = postcode;
        this.polygon = polygon;
        this.eastBound = eastBound;
        this.westBound = westBound;
        this.northBound = northBound;
        this.southBound = southBound;
        this.linkUrl = linkUrl;
        this.level = level;
        this.year = year;
    }
 
    /********** get/set ***********/
    public java.lang.String get_id() {
        return _id;
    }
 
    public void set_id(java.lang.String _id) {
        this._id = _id;
    }
     
    public java.lang.Integer getSchoolId() {
        return schoolId;
    }
 
    public void setSchoolId(java.lang.Integer schoolId) {
        this.schoolId = schoolId;
    }
     
    public java.lang.String getSchoolName() {
        return schoolName;
    }
 
    public void setSchoolName(java.lang.String schoolName) {
        this.schoolName = schoolName;
    }
     
    public java.lang.String getEmail() {
        return email;
    }
 
    public void setEmail(java.lang.String email) {
        this.email = email;
    }
     
    public java.lang.String getWebsite() {
        return website;
    }
 
    public void setWebsite(java.lang.String website) {
        this.website = website;
    }
     
    public java.lang.String getSector() {
        return sector;
    }
 
    public void setSector(java.lang.String sector) {
        this.sector = sector;
    }
     
    public java.lang.String getGender() {
        return gender;
    }
 
    public void setGender(java.lang.String gender) {
        this.gender = gender;
    }
     
    public java.lang.String getType() {
        return type;
    }
 
    public void setType(java.lang.String type) {
        this.type = type;
    }
     
    public java.util.ArrayList getBasePoint() {
        return basePoint;
    }
 
    public void setBasePoint(java.util.ArrayList basePoint) {
        this.basePoint = basePoint;
    }
     
    public java.lang.String getAddress() {
        return address;
    }
 
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
     
    public java.lang.String getSuburb() {
        return suburb;
    }
 
    public void setSuburb(java.lang.String suburb) {
        this.suburb = suburb;
    }
     
    public java.lang.String getStreetName() {
        return streetName;
    }
 
    public void setStreetName(java.lang.String streetName) {
        this.streetName = streetName;
    }
     
    public java.lang.String getState() {
        return state;
    }
 
    public void setState(java.lang.String state) {
        this.state = state;
    }
     
    public java.lang.String getPostcode() {
        return postcode;
    }
 
    public void setPostcode(java.lang.String postcode) {
        this.postcode = postcode;
    }
     
    public java.util.ArrayList getPolygon() {
        return polygon;
    }
 
    public void setPolygon(java.util.ArrayList polygon) {
        this.polygon = polygon;
    }
     
    public java.lang.Double getEastBound() {
        return eastBound;
    }
 
    public void setEastBound(java.lang.Double eastBound) {
        this.eastBound = eastBound;
    }
     
    public java.lang.Double getWestBound() {
        return westBound;
    }
 
    public void setWestBound(java.lang.Double westBound) {
        this.westBound = westBound;
    }
     
    public java.lang.Double getNorthBound() {
        return northBound;
    }
 
    public void setNorthBound(java.lang.Double northBound) {
        this.northBound = northBound;
    }
     
    public java.lang.Double getSouthBound() {
        return southBound;
    }
 
    public void setSouthBound(java.lang.Double southBound) {
        this.southBound = southBound;
    }
     
    public java.lang.String getLinkUrl() {
        return linkUrl;
    }
 
    public void setLinkUrl(java.lang.String linkUrl) {
        this.linkUrl = linkUrl;
    }
     
    public java.lang.Object getLevel() {
        return level;
    }
 
    public void setLevel(java.lang.String level) {
        this.level = level;
    }
     
    public java.lang.String getYear() {
        return year;
    }
 
    public void setYear(java.lang.String year) {
        this.year = year;
    }
    

    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    
    @Override
    public String toString() {
        return "School [_id=" + _id + ", schoolId=" + schoolId + ", schoolName=" + schoolName + ", email=" + email
                + ", website=" + website + ", sector=" + sector + ", gender=" + gender + ", type=" + type
                + ", basePoint=" + basePoint + ", address=" + address + ", suburb=" + suburb + ", streetName="
                + streetName + ", state=" + state + ", postcode=" + postcode + ", polygon=" + polygon + ", eastBound="
                + eastBound + ", westBound=" + westBound + ", northBound=" + northBound + ", southBound=" + southBound
                + ", linkUrl=" + linkUrl + ", level=" + level + ", year=" + year + ", rank=" + rank + "]";
    }

    @SuppressWarnings("unchecked")
    public void initFromSearchHit(SearchHit hit) {
       
        set_id(hit.getId());
        Map<String,Object> result = hit.getSource();
            
        this.schoolName = (String)result.get("school_name");
        this.schoolId = (Integer)result.get("school_id");
        this.email = (String)result.get("email");
        this.website = (String)result.get("website");
        this.sector = (String)result.get("sector");
        this.gender = (String)result.get("gender");
        this.type = (String)result.get("type");
        this.basePoint = (ArrayList<Double>)result.get("base_point");
        this.address = (String)result.get("address");
        this.suburb = (String)result.get("suburb");
        this.streetName = (String)result.get("street_name");
        this.state = (String)result.get("state");
        this.postcode = (String)result.get("postcode");
        if (result.get("polygon") != null) {
            Map<String, Object> map = (Map<String,Object>)result.get("polygon");
            if (map != null) {
                this.polygon = (ArrayList<ArrayList<Double>>)map.get("coordinates");
            }
        }

        
        this.eastBound = (Double)result.get("east_bound");
        this.westBound = (Double)result.get("west_bound");
        this.northBound = (Double)result.get("north_bound");
        this.southBound = (Double)result.get("south_bound");
        this.linkUrl = (String)result.get("link_url");
        this.level = (String)result.get("level");
        this.year = (String)result.get("year");
        this.rank = (Integer)result.get("rank");
    }
    
    
     
}