package org.dubbo.spring.boot.tigerz.aus.entity;

/**
 * This code is generated by Machine
 * @author wangjignci@126.com
 *
 */
public class SuburbRank
{
    /********** attribute ***********/
    private java.lang.String _id;
     
    private java.lang.String name;
     
    private java.lang.String cnName;
     
    private java.lang.Double rentYield;
     
    private java.lang.Double annualGrowth;
     
    private java.lang.Integer medianSoldPrice;
     
    private java.lang.Integer medianRentPrice;
     
    private java.lang.String area;
     
    private java.lang.String areaId;
     
    private java.lang.String region;
     
    private java.lang.String state;
     
    private java.lang.String postCode;
     
    private java.lang.String displayName;
     
    /********** constructors ***********/
    public SuburbRank() {
     
    }
 
    public SuburbRank(java.lang.String _id, java.lang.String name, java.lang.String cnName, java.lang.Double rentYield, java.lang.Double annualGrowth, java.lang.Integer medianSoldPrice, java.lang.Integer medianRentPrice, java.lang.String area, java.lang.String areaId, java.lang.String region, java.lang.String state, java.lang.String postCode, java.lang.String displayName) {
        this._id = _id;
        this.name = name;
        this.cnName = cnName;
        this.rentYield = rentYield;
        this.annualGrowth = annualGrowth;
        this.medianSoldPrice = medianSoldPrice;
        this.medianRentPrice = medianRentPrice;
        this.area = area;
        this.areaId = areaId;
        this.region = region;
        this.state = state;
        this.postCode = postCode;
        this.displayName = displayName;
    }
 
    /********** get/set ***********/
    public java.lang.String get_id() {
        return _id;
    }
 
    public void set_id(java.lang.String _id) {
        this._id = _id;
    }
     
    public java.lang.String getName() {
        return name;
    }
 
    public void setName(java.lang.String name) {
        this.name = name;
    }
     
    public java.lang.String getCnName() {
        return cnName;
    }
 
    public void setCnName(java.lang.String cnName) {
        this.cnName = cnName;
    }
     
    public java.lang.Double getRentYield() {
        return rentYield;
    }
 
    public void setRentYield(java.lang.Double rentYield) {
        this.rentYield = rentYield;
    }
     
    public java.lang.Double getAnnualGrowth() {
        return annualGrowth;
    }
 
    public void setAnnualGrowth(java.lang.Double annualGrowth) {
        this.annualGrowth = annualGrowth;
    }
     
    public java.lang.Integer getMedianSoldPrice() {
        return medianSoldPrice;
    }
 
    public void setMedianSoldPrice(java.lang.Integer medianSoldPrice) {
        this.medianSoldPrice = medianSoldPrice;
    }
     
    public java.lang.Integer getMedianRentPrice() {
        return medianRentPrice;
    }
 
    public void setMedianRentPrice(java.lang.Integer medianRentPrice) {
        this.medianRentPrice = medianRentPrice;
    }
     
    public java.lang.String getArea() {
        return area;
    }
 
    public void setArea(java.lang.String area) {
        this.area = area;
    }
     
    public java.lang.String getAreaId() {
        return areaId;
    }
 
    public void setAreaId(java.lang.String areaId) {
        this.areaId = areaId;
    }
     
    public java.lang.String getRegion() {
        return region;
    }
 
    public void setRegion(java.lang.String region) {
        this.region = region;
    }
     
    public java.lang.String getState() {
        return state;
    }
 
    public void setState(java.lang.String state) {
        this.state = state;
    }
     
    public java.lang.String getPostCode() {
        return postCode;
    }
 
    public void setPostCode(java.lang.String postCode) {
        this.postCode = postCode;
    }
     
    public java.lang.String getDisplayName() {
        return displayName;
    }
 
    public void setDisplayName(java.lang.String displayName) {
        this.displayName = displayName;
    }
     
}