package org.dubbo.spring.boot.tigerz.aus.entity;

/**
 * This code is generated by Machine
 * @author wangjignci@126.com
 *
 */
public class UserStat
{
    /********** attribute ***********/
    private java.lang.String _id;
     
    private java.lang.String uid;
     
    private java.lang.Integer utype;
     
    private java.lang.Long updateSearchTime;
     
    private java.lang.Integer searchCount;
     
    private java.lang.String lastLoginDate;
     
    private java.lang.Integer loginDays;
     
    private java.util.ArrayList loginTime;
     
    private java.lang.String IP;
     
    private java.lang.Long updateViewTime;
     
    private java.util.ArrayList searchPropertyTypeNew;
     
    private java.lang.String searchPriceNew;
     
    private java.lang.String searchBedNew;
     
    private java.lang.String searchBathNew;
     
    private java.lang.String searchParkingNew;
     
    private java.lang.Boolean isReduceIn24;
     
    private org.bson.Document view;
     
    private java.lang.String viewNew;
    
    private org.bson.Document searchSuburb;
    
    private java.lang.String searchSuburbNew;
     
    private java.lang.Integer viewCount;
     
    private org.bson.Document suburb;
     
    private java.lang.String suburbNew;
     
    private org.bson.Document street;
     
    private java.lang.String streetNew;
     
    private org.bson.Document housePrice;
     
    private java.lang.Integer housePriceNew;
     
    private org.bson.Document bed;
     
    private java.lang.Integer bedNew;
     
    private org.bson.Document bath;
     
    private java.lang.Integer bathNew;
     
    private org.bson.Document parking;
     
    private java.lang.Integer parkingNew;
     
    /********** constructors ***********/
    public UserStat() {
     
    }
 
    public UserStat(java.lang.String _id, java.lang.String uid, java.lang.Integer utype, java.lang.Long updateSearchTime, java.lang.Integer searchCount, java.lang.String lastLoginDate, java.lang.Integer loginDays, java.util.ArrayList loginTime, java.lang.String iP, java.lang.Long updateViewTime, java.util.ArrayList searchPropertyTypeNew, java.lang.String searchPriceNew, java.lang.String searchBedNew, java.lang.String searchBathNew, java.lang.String searchParkingNew, java.lang.Boolean isReduceIn24, org.bson.Document view, java.lang.String viewNew, java.lang.Integer viewCount, org.bson.Document suburb, java.lang.String suburbNew, org.bson.Document street, java.lang.String streetNew, org.bson.Document housePrice, java.lang.Integer housePriceNew, org.bson.Document bed, java.lang.Integer bedNew, org.bson.Document bath, java.lang.Integer bathNew, org.bson.Document parking, java.lang.Integer parkingNew) {
        this._id = _id;
        this.uid = uid;
        this.utype = utype;
        this.updateSearchTime = updateSearchTime;
        this.searchCount = searchCount;
        this.lastLoginDate = lastLoginDate;
        this.loginDays = loginDays;
        this.loginTime = loginTime;
        this.updateViewTime = updateViewTime;
        this.searchPropertyTypeNew = searchPropertyTypeNew;
        this.searchPriceNew = searchPriceNew;
        this.searchBedNew = searchBedNew;
        this.searchBathNew = searchBathNew;
        this.searchParkingNew = searchParkingNew;
        this.isReduceIn24 = isReduceIn24;
        this.view = view;
        this.viewNew = viewNew;
        this.viewCount = viewCount;
        this.suburb = suburb;
        this.suburbNew = suburbNew;
        this.street = street;
        this.streetNew = streetNew;
        this.housePrice = housePrice;
        this.housePriceNew = housePriceNew;
        this.bed = bed;
        this.bedNew = bedNew;
        this.bath = bath;
        this.bathNew = bathNew;
        this.parking = parking;
        this.parkingNew = parkingNew;
    }
 
    /********** get/set ***********/
    public java.lang.String get_id() {
        return _id;
    }
 
    public void set_id(java.lang.String _id) {
        this._id = _id;
    }
     
    public java.lang.String getUid() {
        return uid;
    }
 
    public void setUid(java.lang.String uid) {
        this.uid = uid;
    }
     
    public java.lang.Integer getUtype() {
        return utype;
    }
 
    public void setUtype(java.lang.Integer utype) {
        this.utype = utype;
    }
     
    public java.lang.Long getUpdateSearchTime() {
        return updateSearchTime;
    }
 
    public void setUpdateSearchTime(java.lang.Long updateSearchTime) {
        this.updateSearchTime = updateSearchTime;
    }
     
    public java.lang.Integer getSearchCount() {
        return searchCount;
    }
 
    public void setSearchCount(java.lang.Integer searchCount) {
        this.searchCount = searchCount;
    }
     
    public java.lang.String getLastLoginDate() {
        return lastLoginDate;
    }
 
    public void setLastLoginDate(java.lang.String lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
     
    public java.lang.Integer getLoginDays() {
        return loginDays;
    }
 
    public void setLoginDays(java.lang.Integer loginDays) {
        this.loginDays = loginDays;
    }
     
    public java.util.ArrayList getLoginTime() {
        return loginTime;
    }
 
    public void setLoginTime(java.util.ArrayList loginTime) {
        this.loginTime = loginTime;
    }
     
    
     
    public java.lang.String getIP() {
        return IP;
    }

    public void setIP(java.lang.String iP) {
        IP = iP;
    }

    public java.lang.Long getUpdateViewTime() {
        return updateViewTime;
    }
 
    public void setUpdateViewTime(java.lang.Long updateViewTime) {
        this.updateViewTime = updateViewTime;
    }
     
    public java.util.ArrayList getSearchPropertyTypeNew() {
        return searchPropertyTypeNew;
    }
 
    public void setSearchPropertyTypeNew(java.util.ArrayList searchPropertyTypeNew) {
        this.searchPropertyTypeNew = searchPropertyTypeNew;
    }
     
    public java.lang.String getSearchPriceNew() {
        return searchPriceNew;
    }
 
    public void setSearchPriceNew(java.lang.String searchPriceNew) {
        this.searchPriceNew = searchPriceNew;
    }
     
    public java.lang.String getSearchBedNew() {
        return searchBedNew;
    }
 
    public void setSearchBedNew(java.lang.String searchBedNew) {
        this.searchBedNew = searchBedNew;
    }
     
    public java.lang.String getSearchBathNew() {
        return searchBathNew;
    }
 
    public void setSearchBathNew(java.lang.String searchBathNew) {
        this.searchBathNew = searchBathNew;
    }
     
    public java.lang.String getSearchParkingNew() {
        return searchParkingNew;
    }
 
    public void setSearchParkingNew(java.lang.String searchParkingNew) {
        this.searchParkingNew = searchParkingNew;
    }
     
    public java.lang.Boolean getIsReduceIn24() {
        return isReduceIn24;
    }
 
    public void setIsReduceIn24(java.lang.Boolean isReduceIn24) {
        this.isReduceIn24 = isReduceIn24;
    }
     
    public org.bson.Document getView() {
        return view;
    }
 
    public void setView(org.bson.Document view) {
        this.view = view;
    }
     
    public java.lang.String getViewNew() {
        return viewNew;
    }
 
    public void setViewNew(java.lang.String viewNew) {
        this.viewNew = viewNew;
    }
     
    public java.lang.Integer getViewCount() {
        return viewCount;
    }
 
    public void setViewCount(java.lang.Integer viewCount) {
        this.viewCount = viewCount;
    }
     
    public org.bson.Document getSuburb() {
        return suburb;
    }
 
    public void setSuburb(org.bson.Document suburb) {
        this.suburb = suburb;
    }
     
    public java.lang.String getSuburbNew() {
        return suburbNew;
    }
 
    public void setSuburbNew(java.lang.String suburbNew) {
        this.suburbNew = suburbNew;
    }
     
    public org.bson.Document getStreet() {
        return street;
    }
 
    public void setStreet(org.bson.Document street) {
        this.street = street;
    }
     
    public java.lang.String getStreetNew() {
        return streetNew;
    }
 
    public void setStreetNew(java.lang.String streetNew) {
        this.streetNew = streetNew;
    }
     
    public org.bson.Document getHousePrice() {
        return housePrice;
    }
 
    public void setHousePrice(org.bson.Document housePrice) {
        this.housePrice = housePrice;
    }
     
    public java.lang.Integer getHousePriceNew() {
        return housePriceNew;
    }
 
    public void setHousePriceNew(java.lang.Integer housePriceNew) {
        this.housePriceNew = housePriceNew;
    }
     
    public org.bson.Document getBed() {
        return bed;
    }
 
    public void setBed(org.bson.Document bed) {
        this.bed = bed;
    }
     
    public java.lang.Integer getBedNew() {
        return bedNew;
    }
 
    public void setBedNew(java.lang.Integer bedNew) {
        this.bedNew = bedNew;
    }
     
    public org.bson.Document getBath() {
        return bath;
    }
 
    public void setBath(org.bson.Document bath) {
        this.bath = bath;
    }
     
    public java.lang.Integer getBathNew() {
        return bathNew;
    }
 
    public void setBathNew(java.lang.Integer bathNew) {
        this.bathNew = bathNew;
    }
     
    public org.bson.Document getParking() {
        return parking;
    }
 
    public void setParking(org.bson.Document parking) {
        this.parking = parking;
    }
     
    public java.lang.Integer getParkingNew() {
        return parkingNew;
    }
 
    public void setParkingNew(java.lang.Integer parkingNew) {
        this.parkingNew = parkingNew;
    }
    

    public org.bson.Document getSearchSuburb() {
        return searchSuburb;
    }

    public void setSearchSuburb(org.bson.Document searchSuburb) {
        this.searchSuburb = searchSuburb;
    }

    public java.lang.String getSearchSuburbNew() {
        return searchSuburbNew;
    }

    public void setSearchSuburbNew(java.lang.String searchSuburbNew) {
        this.searchSuburbNew = searchSuburbNew;
    }

    @Override
    public String toString() {
        return "UserStat [_id=" + _id + ", uid=" + uid + ", utype=" + utype + ", updateSearchTime=" + updateSearchTime
                + ", searchCount=" + searchCount + ", lastLoginDate=" + lastLoginDate + ", loginDays=" + loginDays
                + ", loginTime=" + loginTime + ", iP=" + IP + ", updateViewTime=" + updateViewTime
                + ", searchPropertyTypeNew=" + searchPropertyTypeNew + ", searchPriceNew=" + searchPriceNew
                + ", searchBedNew=" + searchBedNew + ", searchBathNew=" + searchBathNew + ", searchParkingNew="
                + searchParkingNew + ", isReduceIn24=" + isReduceIn24 + ", view=" + view + ", viewNew=" + viewNew
                + ", viewCount=" + viewCount + ", suburb=" + suburb + ", suburbNew=" + suburbNew + ", street=" + street
                + ", streetNew=" + streetNew + ", housePrice=" + housePrice + ", housePriceNew=" + housePriceNew
                + ", bed=" + bed + ", bedNew=" + bedNew + ", bath=" + bath + ", bathNew=" + bathNew + ", parking="
                + parking + ", parkingNew=" + parkingNew + "]";
    }
     
    
}
